# Generated by Django 4.2 on 2023-10-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
