# Generated by Django 4.2 on 2023-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneForDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('intervals', models.JSONField()),
            ],
        ),
    ]
