# Generated by Django 4.2 on 2023-10-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_zonefordb'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonefordb',
            name='latOfCenter',
            field=models.FloatField(default=0.0),
        ),
    ]
