# Generated by Django 4.2 on 2023-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_zonefordb_stepofazimuth'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonefordb',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
    ]
