# Generated by Django 4.2 on 2023-10-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_zonefordb_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pods', models.JSONField()),
            ],
        ),
    ]
