# Generated by Django 4.2 on 2023-11-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_tracean'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('polygons', models.JSONField()),
            ],
        ),
    ]
