# Generated by Django 4.2 on 2023-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_airportbuilding'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportbuilding',
            name='max_lat',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='airportbuilding',
            name='max_lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='airportbuilding',
            name='min_lat',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='airportbuilding',
            name='min_lon',
            field=models.FloatField(default=0.0),
        ),
    ]
